### ISSUE TITLE
Can't specify releaseVersion and developVersion on command line with grunt@1.0.1

### ISSUE THREAD

**Issue by PierreFritsch** [SunGard-Labs/grunt-sg-release#10]
Hi folks

Specifying a `releaseVersion` and `developVersion` on command line works fine with `grunt@0.4.5`, but it seems that `grunt@1.0.1` changed the handling of the arguments passed with the command-line interface (using `grunt-cli@1.2.0` in both cases).

To make it more concrete, the following command works fine with `grunt@0.4.5`:

    grunt release --releaseVersion 1.3.0 --developVersion 1.4.0-rc

but with `grunt@1.0.1` it fails with the following error message:

    Error: Task "1.3.0" not found.

Best regards
Pierre

**Comment by passelin** [comment]
I haven't used grunt or this plugin in a while, but looking at some examples out there, it seems that using '=' is the way to go. Can you try that?

```
grunt release --releaseVersion=1.3.0 --developVersion=1.4.0-rc
```

**Comment by PierreFritsch** [comment]
Thanks it works! Created a pull request to update the README.
